input:
  file_path: '/home/users/tao.cai/Visualization/input_file/badcase_outputs.txt'
  label: 5
  vector: '8, 135'
  picture_path: 0
  roi: '1, 4'

function:
  resize: 4
  shownum: 0
  noimage: 0
  show_image: False
  save_tmp: True
  location: './logs'
  tagname: 'face_anti-spoofing'

